"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Locale = 'en' | 'es' | 'fr' | 'ar';

interface Translation {
  [key: string]: string;
}

interface Translations {
  [locale: string]: Translation;
}

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Clean, deduplicated translations per locale
const translations: Translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.skills': 'Skills',
    'nav.projects': 'Projects',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.resume': 'Resume',

    'hero.welcome': 'Welcome to FutureStack',
    'hero.tagline': 'Expert Web Developer & Designer',
    'hero.description': 'Crafting digital experiences that convert.',
    'hero.cta': 'Explore My Work',
    'hero.secondary': 'Get in Touch',
    'hero.hire': 'Hire Me',
    'hero.projects': 'View Projects',

    'about.title': 'About Me',
    'about.subtitle': 'Passionate Web Designer & Developer',
    'about.description': 'I\'m Masroor Ibrahim, a web developer specializing in modern, responsive, high-performance websites.',
    'about.clients': 'Happy Clients',

    'services.title': 'My Services',
    'services.subtitle': 'What I Offer',
    'services.description': 'End-to-end solutions from idea to launch.',
    'services.cta': 'Ready to start your project?',
    'services.ctaLink': 'Let\'s talk!',
    'services.webdev.title': 'Web Development',
    'services.webdev.desc': 'Custom websites with React, Next.js and TypeScript.',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Designs that enhance UX and drive conversions.',
    'services.ecommerce.title': 'E-commerce Solutions',
    'services.ecommerce.desc': 'Online stores with secure payments and inventory.',
    'services.seo.title': 'SEO Optimization',
    'services.seo.desc': 'Improve search rankings and organic traffic.',

    'projects.portfolio': 'Portfolio',
    'projects.featured': 'Featured Projects',
    'projects.viewDetails': 'View Details',
    'projects.featuredLabel': 'Featured',
    'projects.featuredProject': 'Featured Project',
    'projects.techUsed': 'Technologies Used',
    'projects.description': 'Projects showcasing design, development and problem-solving.',
    'projects.viewMore': 'View More on GitHub',
    'projects.title': 'My Projects',
    'projects.subtitle': 'Recent Work',
    'projects.view': 'View Project',
    'projects.live': 'Live Demo',
    'projects.code': 'View Code',

    'blog.title': 'Blog',
    'blog.subtitle': 'Latest Insights',
    'blog.description': 'Thoughts on design, development, and technology.',
    'blog.viewAll': 'View All Articles',

    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Let\'s Work Together',
    'contact.description': 'Have a project in mind? Send me a message.',
    'contact.available': 'Available for new projects',
    'contact.info.title': 'Contact Information',
    'contact.info.description': 'Available for freelance, full-time, and consulting.',
    'contact.card.email': 'Email',
    'contact.card.phone': 'Phone',
    'contact.card.collaboration': 'Collaboration',
    'contact.followMe': 'Follow me',
    'contact.helpTitle': 'How I Can Help',
    'contact.helpBody': 'Need help planning your next website or app? Here are the details that help me deliver the best outcome:',
    'contact.help.list.goal': 'Your project goal and desired result',
    'contact.help.list.audience': 'Your target audience or customer',
    'contact.help.list.timeline': 'Expected launch timeline',
    'contact.help.list.branding': 'Any brand or style direction you prefer',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Your name',
    'contact.form.placeholder.email': 'Your email address',
    'contact.form.placeholder.subject': 'Project subject',
    'contact.form.placeholder.message': 'Tell me about your project',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.sent': 'Message Sent!',
    'contact.thankYou': 'Thank you! I\'ll get back to you within 24 hours.',

    'footer.built': 'Built with',
    'footer.rights': 'All rights reserved.',
    'footer.madeWith': 'Made with',
    'footer.by': 'by',

    'skills.title': 'My Skills',
    'skills.subtitle': 'Technical Expertise',

    'landing.title': 'Welcome to FutureStack',
    'landing.description': 'Discover cutting-edge web solutions that transform your digital presence.',
    'landing.explore': 'Explore Projects',
    'landing.talk': 'Talk About Your Project',
    'landing.portfolio': 'Discover the Portfolio',
    'landing.cards.services.title': 'Services & Strategy',
    'landing.cards.services.desc': 'Custom digital products and growth-focused design services.',
    'landing.cards.projects.title': 'Projects & Case Studies',
    'landing.cards.projects.desc': 'Showcase work built for performance and clarity.',
    'landing.cards.insights.title': 'Insights & Growth',
    'landing.cards.insights.desc': 'Articles and ideas for modern web success.',
    'landing.hint': 'Scroll or click to explore',
    'about.hero.title': 'Welcome to FutureStack',
    'about.hero.subtitle': 'Where bold ideas become polished digital experiences.',
    'about.hero.description': 'I build scalable websites, intuitive interfaces, and unforgettable brand journeys that help businesses and founders win online.',
    'about.hero.label1': 'Mission-driven web development',
    'about.hero.label2': 'Design-led brand stories',
    'about.hero.label3': 'Growth-focused digital products',
    'services.hero.title': 'Bespoke Development, Designed to Convert',
    'services.hero.subtitle': 'Solutions crafted for brands that need a polished digital presence and measurable growth.',
    'services.hero.description': 'From launch-ready websites to full-featured digital products, I create digital experiences that attract customers and support business goals.',
    'services.hero.label1': 'Strategy-led development',
    'services.hero.label2': 'Conversion-focused design',
    'services.hero.label3': 'Reliable long-term support',
    'hero.stats.experience': 'Years Experience',
    'hero.stats.projects': 'Projects Completed',
    'hero.stats.satisfaction': 'Client Satisfaction',
    'common.scroll': 'Scroll',
    'services.testimonials.heading': 'Client Success',
    'services.testimonials.title': 'What My Clients Say',
    'services.testimonials.description': 'Hear directly from businesses that have partnered with FutureStack to achieve their digital goals.',
    'services.advantages': 'Advantages',
    'services.advantagesTitle': 'Why Partner With FutureStack',
    'services.compare': 'Compare',
    'services.packages.title': 'Choose Your Perfect Package',
    'services.pricing.title': 'Pricing',
    'services.pricing.description': 'Transparent investment models designed to suit businesses at different stages of growth.',
    'services.mostPopular': 'MOST POPULAR',
    'services.getStarted': 'Get Started',
    'skills.hero.title': 'Mastery in Modern Web Development',
    'skills.hero.subtitle': 'A powerful toolkit of design, development, and performance skills for brands that demand excellence.',
    'skills.hero.description': 'I transform ideas into fast, user-first websites and apps that feel polished, perform beautifully, and build trust online.',
    'skills.hero.label1': 'Real client work',
    'skills.hero.label2': 'Modern toolchain',
    'skills.hero.label3': 'Design to deployment',
    'projects.hero.title': 'Work That Makes an Impact',
    'projects.hero.subtitle': 'Discover carefully crafted digital products built for growth, engagement, and strong brand presence.',
    'projects.hero.description': 'Browse website and app projects designed to support business goals, delight users, and convert visitors into customers.',
    'projects.hero.label1': 'Strategy-led builds',
    'projects.hero.label2': 'Performance-first UX',
    'projects.hero.label3': 'Real-world impact',
    'blog.hero.title': 'Ideas That Help You Build Better',
    'blog.hero.subtitle': 'Practical insights, tutorials, and industry thinking for modern web development.',
    'blog.hero.description': 'Stay ahead with articles that cover performance, UX, design systems, and building digital experiences that convert.',
    'blog.hero.label1': 'Practical how-tos',
    'blog.hero.label2': 'Design and dev insights',
    'blog.hero.label3': 'Growth-driven ideas',
    'contact.hero.title': 'Let\'s Build Something Exceptional',
    'contact.hero.subtitle': 'Ready to launch your next website or app? I’m here to help you turn bold ideas into polished online experiences.',
    'contact.hero.description': 'From fast MVPs to full-featured digital products, I create websites and apps that attract clients, build trust, and support your business goals.',
    'contact.hero.label1': 'Response within 24 hours',
    'contact.hero.label2': 'Available for new projects',
    'contact.hero.label3': 'Flexible remote collaboration',

    'about.stats.experience': 'Years Experience',
    'about.stats.clients': 'Happy Clients',
    'about.stats.projects': 'Major Projects',
    'about.stats.coffee': 'Cups of Coffee',

    'testimonials.title': 'Client Testimonials',
    'testimonials.subtitle': 'What People Say',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Common Questions',

    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.viewAll': 'View All',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.tryAgain': 'Try Again',
  },

  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Mí',
    'nav.services': 'Servicios',
    'nav.skills': 'Habilidades',
    'nav.projects': 'Proyectos',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacto',
    'nav.resume': 'Currículum',

    'hero.welcome': 'Bienvenido a FutureStack',
    'hero.tagline': 'Desarrollador Web Experto',
    'hero.description': 'Creando experiencias digitales que convierten.',
    'hero.cta': 'Explorar Mi Trabajo',
    'hero.secondary': 'Contactar',
    'hero.hire': 'Contrátame',
    'hero.projects': 'Ver Proyectos',

    'about.title': 'Sobre Mí',
    'about.subtitle': 'Diseñador y Desarrollador Web Apasionado',
    'about.description': 'Soy Masroor Ibrahim, desarrollador web con experiencia en sitios modernos y de alto rendimiento.',
    'about.clients': 'Clientes Satisfechos',

    'services.title': 'Mis Servicios',
    'services.subtitle': 'Lo Que Ofrezco',
    'services.description': 'Soluciones completas desde la idea hasta el lanzamiento.',
    'services.cta': '¿Listo para empezar tu proyecto?',
    'services.ctaLink': '¡Hablemos!',
    'services.webdev.title': 'Desarrollo Web',
    'services.webdev.desc': 'Sitios web personalizados con React, Next.js y TypeScript.',
    'services.uiux.title': 'Diseño UI/UX',
    'services.uiux.desc': 'Diseños que mejoran la experiencia y aumentan conversiones.',
    'services.ecommerce.title': 'Soluciones de Comercio Electrónico',
    'services.ecommerce.desc': 'Tiendas online con pagos seguros e inventario.',
    'services.seo.title': 'Optimización SEO',
    'services.seo.desc': 'Mejora el posicionamiento y el tráfico orgánico.',

    'projects.portfolio': 'Portafolio',
    'projects.featured': 'Proyectos Destacados',
    'projects.viewDetails': 'Ver Detalles',
    'projects.featuredLabel': 'Destacado',
    'projects.featuredProject': 'Proyecto Destacado',
    'projects.techUsed': 'Tecnologías Usadas',
    'projects.description': 'Proyectos que muestran mi experiencia en diseño y desarrollo.',
    'projects.viewMore': 'Ver más en GitHub',
    'projects.title': 'Mis Proyectos',
    'projects.subtitle': 'Trabajo Reciente',
    'projects.view': 'Ver Proyecto',
    'projects.live': 'Demostración',
    'projects.code': 'Ver Código',

    'blog.title': 'Blog',
    'blog.subtitle': 'Últimas Ideas',
    'blog.description': 'Reflexiones sobre diseño y desarrollo.',
    'blog.viewAll': 'Ver todos los artículos',

    'contact.title': 'Ponte en Contacto',
    'contact.subtitle': 'Trabajemos Juntos',
    'contact.description': '¿Tienes un proyecto en mente? Envíame un mensaje.',
    'contact.available': 'Disponible para nuevos proyectos',
    'contact.info.title': 'Información de Contacto',
    'contact.info.description': 'Disponible para freelance, tiempo completo y consultoría.',
    'contact.card.email': 'Correo',
    'contact.card.phone': 'Teléfono',
    'contact.card.collaboration': 'Colaboración',
    'contact.followMe': 'Sígueme',
    'contact.helpTitle': 'Cómo Puedo Ayudar',
    'contact.helpBody': '¿Necesitas ayuda para planificar tu próximo sitio web o aplicación? Aquí están los detalles que me ayudan a entregar el mejor resultado:',
    'contact.help.list.goal': 'El objetivo de tu proyecto y el resultado deseado',
    'contact.help.list.audience': 'Tu audiencia objetivo o perfil de cliente',
    'contact.help.list.timeline': 'Plazo de lanzamiento esperado',
    'contact.help.list.branding': 'Cualquier dirección de marca o estilo que prefieras',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Correo electrónico',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.placeholder.name': 'Tu nombre',
    'contact.form.placeholder.email': 'Tu correo electrónico',
    'contact.form.placeholder.subject': 'Asunto del proyecto',
    'contact.form.placeholder.message': 'Cuéntame sobre tu proyecto',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.sent': '¡Mensaje Enviado!',
    'contact.thankYou': 'Gracias! Te responderé pronto.',

    'footer.built': 'Construido con',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.madeWith': 'Hecho con',
    'footer.by': 'por',

    'skills.title': 'Mis Habilidades',
    'skills.subtitle': 'Experiencia Técnica',

    'landing.title': 'Bienvenido a FutureStack',
    'landing.description': 'Descubre soluciones web que transforman tu presencia digital.',
    'landing.explore': 'Explorar Proyectos',
    'landing.talk': 'Hablar sobre tu proyecto',
    'landing.portfolio': 'Descubre el Portafolio',
    'landing.cards.services.title': 'Servicios y Estrategia',
    'landing.cards.services.desc': 'Productos digitales personalizados y servicios de diseño.',
    'landing.cards.projects.title': 'Proyectos y Casos de Estudio',
    'landing.cards.projects.desc': 'Trabajo enfocado en rendimiento y claridad.',
    'landing.cards.insights.title': 'Ideas y Crecimiento',
    'landing.cards.insights.desc': 'Artículos e ideas para el éxito web moderno.',
    'landing.hint': 'Desplázate o haz clic para explorar',
    'about.hero.title': 'Bienvenido a FutureStack',
    'about.hero.subtitle': 'Donde las ideas audaces se convierten en experiencias digitales pulidas.',
    'about.hero.description': 'Construyo sitios web escalables, interfaces intuitivas y trayectorias de marca inolvidables que ayudan a empresas y fundadores a ganar en línea.',
    'about.hero.label1': 'Desarrollo web orientado a la misión',
    'about.hero.label2': 'Historias de marca guiadas por el diseño',
    'about.hero.label3': 'Productos digitales centrados en el crecimiento',
    'services.hero.title': 'Desarrollo a medida, diseñado para convertir',
    'services.hero.subtitle': 'Soluciones creadas para marcas que necesitan una presencia digital pulida y crecimiento medible.',
    'services.hero.description': 'Desde sitios listos para lanzamiento hasta productos digitales completos, creo experiencias que atraen clientes y apoyan objetivos comerciales.',
    'services.hero.label1': 'Desarrollo guiado por estrategia',
    'services.hero.label2': 'Diseño enfocado en conversiones',
    'services.hero.label3': 'Soporte confiable a largo plazo',
    'hero.stats.experience': 'Años de experiencia',
    'hero.stats.projects': 'Proyectos realizados',
    'hero.stats.satisfaction': 'Satisfacción del cliente',
    'common.scroll': 'Desplázate',
    'services.testimonials.heading': 'Éxito del Cliente',
    'services.testimonials.title': 'Lo que dicen mis clientes',
    'services.testimonials.description': 'Escucha directamente a las empresas que se han asociado con FutureStack para alcanzar sus objetivos digitales.',
    'services.advantages': 'Ventajas',
    'services.advantagesTitle': 'Por qué asociarse con FutureStack',
    'services.compare': 'Comparar',
    'services.packages.title': 'Elige tu paquete perfecto',
    'services.pricing.title': 'Precios',
    'services.pricing.description': 'Modelos de inversión transparentes diseñados para adaptarse a empresas en diferentes etapas de crecimiento.',
    'services.mostPopular': 'EL MÁS POPULAR',
    'services.getStarted': 'Comenzar',
    'skills.hero.title': 'Dominio en el desarrollo web moderno',
    'skills.hero.subtitle': 'Un conjunto potente de habilidades de diseño, desarrollo y rendimiento para marcas que exigen excelencia.',
    'skills.hero.description': 'Transformo ideas en sitios y aplicaciones rápidos y pensados para el usuario, con acabados pulidos, rendimiento excelente y confianza en línea.',
    'skills.hero.label1': 'Trabajo real con clientes',
    'skills.hero.label2': 'Herramientas modernas',
    'skills.hero.label3': 'Del diseño al despliegue',
    'projects.hero.title': 'Trabajo que genera impacto',
    'projects.hero.subtitle': 'Descubre productos digitales diseñados para crecimiento, compromiso y presencia de marca sólida.',
    'projects.hero.description': 'Explora proyectos web y de aplicaciones diseñados para apoyar objetivos comerciales, encantar usuarios y convertir visitantes en clientes.',
    'projects.hero.label1': 'Construcciones guiadas por estrategia',
    'projects.hero.label2': 'UX centrado en el rendimiento',
    'projects.hero.label3': 'Impacto en el mundo real',
    'blog.hero.title': 'Ideas para ayudarte a construir mejor',
    'blog.hero.subtitle': 'Ideas prácticas, tutoriales y pensamiento de la industria para el desarrollo web moderno.',
    'blog.hero.description': 'Mantente al día con artículos sobre rendimiento, UX, sistemas de diseño y experiencias digitales que convierten.',
    'blog.hero.label1': 'Guías prácticas',
    'blog.hero.label2': 'Ideas de diseño y desarrollo',
    'blog.hero.label3': 'Ideas orientadas al crecimiento',
    'contact.hero.title': 'Vamos a construir algo excepcional',
    'contact.hero.subtitle': '¿Listo para lanzar tu próximo sitio web o aplicación? Estoy aquí para ayudarte a convertir ideas audaces en experiencias en línea pulidas.',
    'contact.hero.description': 'Desde MVPs rápidos hasta productos digitales completos, creo sitios y aplicaciones que atraen clientes, generan confianza y respaldan tus metas comerciales.',
    'contact.hero.label1': 'Respuesta en 24 horas',
    'contact.hero.label2': 'Disponible para nuevos proyectos',
    'contact.hero.label3': 'Colaboración remota flexible',

    'testimonials.title': 'Testimonios de Clientes',
    'testimonials.subtitle': 'Lo Que Dicen',
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Preguntas Comunes',

    'common.readMore': 'Leer Más',
    'common.learnMore': 'Saber Más',
    'common.viewAll': 'Ver Todo',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error',
    'common.tryAgain': 'Intentar de Nuevo',
  },

  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.skills': 'Compétences',
    'nav.projects': 'Projets',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.resume': 'CV',

    'hero.welcome': 'Bienvenue sur FutureStack',
    'hero.tagline': 'Développeur Web Expert',
    'hero.description': 'Création d\'expériences numériques qui convertissent.',
    'hero.cta': 'Explorer Mon Travail',
    'hero.secondary': 'Me Contacter',
    'hero.hire': 'Engagez-moi',
    'hero.projects': 'Voir les Projets',

    'about.title': 'À Propos',
    'about.subtitle': 'Designer et Développeur Web Passionné',
    'about.description': 'Je suis Masroor Ibrahim, développeur web spécialisé dans des sites modernes et performants.',
    'about.clients': 'Clients Satisfaits',

    'services.title': 'Mes Services',
    'services.subtitle': 'Ce Que Je Propose',
    'services.webdev.title': 'Développement Web',
    'services.webdev.desc': 'Sites web personnalisés avec React, Next.js et TypeScript.',
    'services.uiux.title': 'Design UI/UX',
    'services.uiux.desc': 'Des designs qui améliorent l\'expérience utilisateur.',
    'services.ecommerce.title': 'Solutions E-commerce',
    'services.ecommerce.desc': 'Boutiques en ligne avec paiements sécurisés.',
    'services.seo.title': 'Optimisation SEO',
    'services.seo.desc': 'Améliorez votre classement et trafic organique.',

    'projects.title': 'Mes Projets',
    'projects.subtitle': 'Travaux Récents',
    'projects.viewDetails': 'Voir les Détails',
    'projects.featuredLabel': 'En Vedette',
    'projects.featuredProject': 'Projet En Vedette',
    'projects.techUsed': 'Technologies Utilisées',
    'projects.view': 'Voir le Projet',
    'projects.live': 'Démo en Ligne',
    'projects.code': 'Voir le Code',

    'blog.title': 'Blog',
    'blog.subtitle': 'Dernières Idées',
    'blog.description': 'Réflexions sur le design et le développement.',
    'blog.viewAll': 'Voir tous les articles',

    'contact.title': 'Me Contacter',
    'contact.subtitle': 'Travaillons Ensemble',
    'contact.description': 'Vous avez un projet ? Envoyez-moi un message.',
    'contact.card.email': 'Email',
    'contact.card.phone': 'Téléphone',
    'contact.card.collaboration': 'Collaboration',
    'contact.followMe': 'Suivez-moi',
    'contact.helpTitle': 'Comment je peux aider',
    'contact.helpBody': 'Besoin d’aide pour planifier votre prochain site web ou application ? Voici les détails qui m’aident à livrer le meilleur résultat :',
    'contact.help.list.goal': 'Objectif de votre projet et résultat souhaité',
    'contact.help.list.audience': 'Public cible ou profil client',
    'contact.help.list.timeline': 'Délai de lancement prévu',
    'contact.help.list.branding': 'Direction de marque ou style préféré',
    'contact.form.name': 'Nom',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Sujet',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Votre nom',
    'contact.form.placeholder.email': 'Votre email',
    'contact.form.placeholder.subject': 'Sujet du projet',
    'contact.form.placeholder.message': 'Parlez-moi de votre projet',
    'contact.send': 'Envoyer le Message',
    'contact.sending': 'Envoi...',
    'contact.sent': 'Message envoyé avec succès !',

    'footer.rights': 'Tous droits réservés.',
    'footer.built': 'Construit avec',
    'footer.by': 'par',

    'skills.title': 'Mes Compétences',
    'skills.subtitle': 'Expertise Technique',

    'landing.title': 'Bienvenue sur FutureStack',
    'landing.description': 'Découvrez des solutions web qui transforment votre présence digitale.',
    'landing.explore': 'Explorer les Projets',
    'landing.hint': 'Faites défiler ou cliquez pour explorer',
    'about.hero.title': 'Bienvenue sur FutureStack',
    'about.hero.subtitle': 'Où les idées audacieuses deviennent des expériences numériques soignées.',
    'about.hero.description': 'Je crée des sites web évolutifs, des interfaces intuitives et des parcours de marque inoubliables qui aident les entreprises et les fondateurs à réussir en ligne.',
    'about.hero.label1': 'Développement web axé sur la mission',
    'about.hero.label2': 'Histoires de marque pilotées par le design',
    'about.hero.label3': 'Produits digitaux orientés croissance',
    'services.hero.title': 'Développement sur mesure, conçu pour convertir',
    'services.hero.subtitle': 'Des solutions conçues pour les marques qui ont besoin d’une présence digitale soignée et d’une croissance mesurable.',
    'services.hero.description': 'Des sites prêts à être lancés aux produits digitaux complets, je crée des expériences qui attirent des clients et soutiennent les objectifs commerciaux.',
    'services.hero.label1': 'Développement guidé par la stratégie',
    'services.hero.label2': 'Design axé sur la conversion',
    'services.hero.label3': 'Support fiable à long terme',
    'hero.stats.experience': 'Années d’expérience',
    'hero.stats.projects': 'Projets réalisés',
    'hero.stats.satisfaction': 'Satisfaction client',
    'common.scroll': 'Faites défiler',
    'services.testimonials.heading': 'Succès client',
    'services.testimonials.title': 'Ce que disent mes clients',
    'services.testimonials.description': 'Écoutez directement les entreprises qui se sont associées à FutureStack pour atteindre leurs objectifs numériques.',
    'services.advantages': 'Avantages',
    'services.advantagesTitle': 'Pourquoi s’associer à FutureStack',
    'services.compare': 'Comparer',
    'services.packages.title': 'Choisissez votre forfait idéal',
    'services.pricing.title': 'Tarification',
    'services.pricing.description': 'Modèles d’investissement transparents conçus pour convenir aux entreprises à différents stades de croissance.',
    'services.mostPopular': 'LE PLUS POPULAIRE',
    'services.getStarted': 'Commencer',
    'skills.hero.title': 'Maîtrise du développement web moderne',
    'skills.hero.subtitle': 'Un ensemble puissant de compétences en design, développement et performance pour les marques exigeantes.',
    'skills.hero.description': 'Je transforme les idées en sites et applications rapides, orientés utilisateur, avec une finition soignée, des performances excellentes et une crédibilité en ligne.',
    'skills.hero.label1': 'Travail client réel',
    'skills.hero.label2': 'Chaîne d’outils moderne',
    'skills.hero.label3': 'Du design au déploiement',
    'projects.hero.title': 'Des travaux qui ont de l’impact',
    'projects.hero.subtitle': 'Découvrez des produits numériques conçus pour la croissance, l’engagement et une forte présence de marque.',
    'projects.hero.description': 'Parcourez des projets web et applications conçus pour soutenir les objectifs commerciaux, séduire les utilisateurs et convertir les visiteurs en clients.',
    'projects.hero.label1': 'Conceptions guidées par la stratégie',
    'projects.hero.label2': 'UX axé performance',
    'projects.hero.label3': 'Impact concret',
    'blog.hero.title': 'Des idées pour vous aider à mieux construire',
    'blog.hero.subtitle': 'Des analyses pratiques, des tutoriels et des réflexions pour le développement web moderne.',
    'blog.hero.description': 'Restez en avance avec des articles sur la performance, l’UX, les systèmes de design et la création d’expériences numériques qui convertissent.',
    'blog.hero.label1': 'Guides pratiques',
    'blog.hero.label2': 'Idées design et dev',
    'blog.hero.label3': 'Idées orientées croissance',
    'contact.hero.title': 'Construisons quelque chose d’exceptionnel',
    'contact.hero.subtitle': 'Prêt à lancer votre prochain site ou application ? Je suis là pour transformer vos idées ambitieuses en expériences en ligne soignées.',
    'contact.hero.description': 'Des MVP rapides aux produits digitaux complets, je crée des sites et applications qui attirent des clients, inspirent confiance et soutiennent vos objectifs.',
    'contact.hero.label1': 'Réponse en 24 heures',
    'contact.hero.label2': 'Disponible pour de nouveaux projets',
    'contact.hero.label3': 'Collaboration à distance flexible',

    'testimonials.title': 'Témoignages Clients',
    'testimonials.subtitle': 'Ce Qu\'ils Disent',
    'faq.title': 'Questions Fréquentes',
    'faq.subtitle': 'Questions Courantes',

    'common.readMore': 'Lire Plus',
    'common.learnMore': 'En Savoir Plus',
    'common.viewAll': 'Tout Voir',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
    'common.tryAgain': 'Réessayer',
  },

  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'عني',
    'nav.services': 'الخدمات',
    'nav.skills': 'المهارات',
    'nav.projects': 'المشاريع',
    'nav.blog': 'المدونة',
    'nav.contact': 'اتصل بي',
    'nav.resume': 'السيرة الذاتية',

    'hero.welcome': 'مرحبًا بكم في FutureStack',
    'hero.tagline': 'مطور ويب خبير',
    'hero.description': 'صياغة تجارب رقمية تحقق التحويلات.',
    'hero.cta': 'استكشف أعمالي',
    'hero.secondary': 'تواصل معي',
    'hero.hire': 'وظفني',
    'hero.projects': 'عرض المشاريع',

    'about.title': 'عني',
    'about.subtitle': 'مصمم ومطور ويب شغوف',
    'about.description': 'أنا مسرور إبراهيم، مطور ويب متخصص في مواقع حديثة وسريعة الاستجابة.',
    'about.clients': 'عملاء سعداء',

    'services.title': 'خدماتي',
    'services.subtitle': 'ماذا أقدم',
    'services.webdev.title': 'تطوير الويب',
    'services.webdev.desc': 'مواقع ويب مخصصة مع React و Next.js و TypeScript.',
    'services.uiux.title': 'تصميم واجهة المستخدم/تجربة المستخدم',
    'services.uiux.desc': 'تصميمات تعزز تجربة المستخدم.',

    'projects.title': 'مشاريعي',
    'projects.subtitle': 'أعمال حديثة',
    'projects.viewDetails': 'عرض التفاصيل',
    'projects.featuredLabel': 'مميز',
    'projects.featuredProject': 'مشروع مميز',
    'projects.techUsed': 'التقنيات المستخدمة',
    'projects.view': 'عرض المشروع',
    'projects.live': 'عرض تجريبي',
    'projects.code': 'عرض الكود',

    'blog.title': 'المدونة',
    'blog.subtitle': 'أحدث المقالات',
    'blog.description': 'أفكار حول التصميم والتطوير.',

    'contact.title': 'اتصل بي',
    'contact.subtitle': 'لنعمل معًا',
    'contact.description': 'هل لديك مشروع في ذهنك؟ أرسل لي رسالة.',
    'contact.card.email': 'البريد الإلكتروني',
    'contact.card.phone': 'الهاتف',
    'contact.card.collaboration': 'التعاون',
    'contact.followMe': 'تابعني',
    'contact.helpTitle': 'كيف يمكنني المساعدة',
    'contact.helpBody': 'هل تحتاج مساعدة في تخطيط موقعك أو تطبيقك القادم؟ إليك التفاصيل التي تساعدني على تقديم أفضل نتيجة:',
    'contact.help.list.goal': 'هدف مشروعك والنتيجة المرجوة',
    'contact.help.list.audience': 'الجمهور المستهدف أو ملف العميل',
    'contact.help.list.timeline': 'الإطار الزمني المتوقع للإطلاق',
    'contact.help.list.branding': 'اتجاه العلامة التجارية أو الأسلوب المفضل',
    'contact.form.name': 'الاسم',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'الرسالة',
    'contact.form.placeholder.name': 'اسمك',
    'contact.form.placeholder.email': 'البريد الإلكتروني الخاص بك',
    'contact.form.placeholder.subject': 'موضوع المشروع',
    'contact.form.placeholder.message': 'أخبرني عن مشروعك',
    'contact.send': 'إرسال الرسالة',
    'contact.sending': 'جارٍ الإرسال...',
    'contact.sent': 'تم الإرسال بنجاح!',

    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.built': 'بني بـ',
    'footer.by': 'بواسطة',

    'skills.title': 'مهاراتي',
    'skills.subtitle': 'الخبرة التقنية',

    'landing.title': 'مرحبًا بك في FutureStack',
    'landing.description': 'اكتشف حلول الويب التي تحول حضورك الرقمي.',
    'landing.hint': 'قم بالتمرير أو النقر لاستكشاف',
    'about.hero.title': 'مرحبًا بك في FutureStack',
    'about.hero.subtitle': 'حيث تتحول الأفكار الجريئة إلى تجارب رقمية مصقولة.',
    'about.hero.description': 'أقوم ببناء مواقع ويب قابلة للتوسع، واجهات مستخدم بديهية، ورحلات علامة تجارية لا تُنسى تساعد الشركات والمؤسسين على النجاح عبر الإنترنت.',
    'about.hero.label1': 'تطوير ويب موجه بالهدف',
    'about.hero.label2': 'قصص علامة تجارية يقودها التصميم',
    'about.hero.label3': 'منتجات رقمية تركز على النمو',
    'services.hero.title': 'تطوير مخصص مصمم للتحويل',
    'services.hero.subtitle': 'حلول مصممة للعلامات التجارية التي تحتاج إلى حضور رقمي مصقول ونمو قابل للقياس.',
    'services.hero.description': 'من المواقع الجاهزة للإطلاق إلى المنتجات الرقمية الكاملة، أخلق تجارب تجذب العملاء وتدعم أهداف العمل.',
    'services.hero.label1': 'تطوير موجه بالاستراتيجية',
    'services.hero.label2': 'تصميم يركز على التحويل',
    'services.hero.label3': 'دعم طويل الأمد موثوق',
    'hero.stats.experience': 'سنوات الخبرة',
    'hero.stats.projects': 'المشاريع المكتملة',
    'hero.stats.satisfaction': 'رضا العملاء',
    'common.scroll': 'مرر',
    'services.testimonials.heading': 'نجاح العملاء',
    'services.testimonials.title': 'ما يقوله عملائي',
    'services.testimonials.description': 'استمع مباشرةً إلى الشركات التي تعاونت مع FutureStack لتحقيق أهدافها الرقمية.',
    'services.advantages': 'المزايا',
    'services.advantagesTitle': 'لماذا الشراكة مع FutureStack',
    'services.compare': 'قارن',
    'services.packages.title': 'اختر باقتك المثالية',
    'services.pricing.title': 'التسعير',
    'services.pricing.description': 'نماذج استثمار شفافة مصممة لتناسب الشركات في مراحل نمو مختلفة.',
    'services.mostPopular': 'الأكثر شيوعًا',
    'services.getStarted': 'البدء',
    'skills.hero.title': 'إتقان تطوير الويب الحديث',
    'skills.hero.subtitle': 'مجموعة قوية من مهارات التصميم والتطوير والأداء للعلامات التجارية التي تطلب التميز.',
    'skills.hero.description': 'أحوّل الأفكار إلى مواقع وتطبيقات سريعة وموجهة للمستخدم، ذات مظهر مصقول وأداء ممتاز وثقة عبر الإنترنت.',
    'skills.hero.label1': 'أعمال عملاء حقيقية',
    'skills.hero.label2': 'سلسلة أدوات حديثة',
    'skills.hero.label3': 'من التصميم إلى النشر',
    'projects.hero.title': 'أعمال تحدث فرقًا',
    'projects.hero.subtitle': 'اكتشف منتجات رقمية مصممة للنمو والتفاعل وحضور علامة تجارية قوي.',
    'projects.hero.description': 'استعرض مشاريع مواقع وتطبيقات مصممة لدعم أهداف العمل وإسعاد المستخدمين وتحويل الزوار إلى عملاء.',
    'projects.hero.label1': 'بناء موجه بالاستراتيجية',
    'projects.hero.label2': 'تجربة مستخدم تركز على الأداء',
    'projects.hero.label3': 'تأثير في العالم الحقيقي',
    'blog.hero.title': 'أفكار تساعدك على البناء بشكل أفضل',
    'blog.hero.subtitle': 'رؤى عملية ودروس وأفكار الصناعة لتطوير الويب الحديث.',
    'blog.hero.description': 'ابق متقدمًا مع مقالات حول الأداء وتجربة المستخدم وأنظمة التصميم وبناء تجارب رقمية تحوّل.',
    'blog.hero.label1': 'إرشادات عملية',
    'blog.hero.label2': 'أفكار التصميم والتطوير',
    'blog.hero.label3': 'أفكار موجهة للنمو',
    'contact.hero.title': 'لننشئ شيئًا استثنائيًا',
    'contact.hero.subtitle': 'هل أنت جاهز لإطلاق موقعك أو تطبيقك القادم؟ أنا هنا لتحويل أفكارك الجريئة إلى تجارب رقمية مصقولة.',
    'contact.hero.description': 'من MVPs سريعة إلى منتجات رقمية كاملة، أصنع مواقع وتطبيقات تجذب العملاء وتبني الثقة وتدعم أهدافك.',
    'contact.hero.label1': 'الرد خلال 24 ساعة',
    'contact.hero.label2': 'متاح لمشاريع جديدة',
    'contact.hero.label3': 'تعاون مرن عن بُعد',

    'testimonials.title': 'شهادات العملاء',
    'testimonials.subtitle': 'ماذا يقولون',
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'أسئلة شائعة',

    'common.readMore': 'اقرأ المزيد',
    'common.learnMore': 'اعرف المزيد',
    'common.viewAll': 'عرض الكل',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.loading': 'جار التحميل...',
    'common.error': 'حدث خطأ',
    'common.tryAgain': 'حاول مرة أخرى',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLocale = localStorage.getItem('locale') as Locale;
    const initialLocale = savedLocale && ['en', 'es', 'fr', 'ar'].includes(savedLocale) ? savedLocale : 'en';
    setLocaleState(initialLocale);
    document.documentElement.lang = initialLocale;
    document.documentElement.dir = initialLocale === 'ar' ? 'rtl' : 'ltr';
    setMounted(true);
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('locale', newLocale);
    document.documentElement.lang = newLocale;
    document.documentElement.dir = newLocale === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    if (!mounted) return '';
    const localeTranslations = translations[locale];
    if (!localeTranslations) {
      console.warn(`Translations for locale "${locale}" not found.`);
      return key;
    }
    return localeTranslations[key] ?? key;
  };

  if (!mounted) return null;

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};

export { translations };
